# Generated by Django 5.2.3 on 2025-06-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='medical_doc',
            field=models.FileField(blank=True, null=True, upload_to='medical_docs/'),
        ),
    ]
