# Generated by Django 5.2.3 on 2025-06-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_message_replied_at_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='doubt_file',
            field=models.FileField(blank=True, null=True, upload_to='doubt_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_file',
            field=models.FileField(blank=True, null=True, upload_to='reply_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
